name: Feature Selection

on:
  push:
    branches:
      - main
    paths:
      - scripts/feature_selection.py
      - .github/workflows/feature_selection.yml

jobs:
  feature-selection:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: 📦 Install dependencies
        run: |
          pip install boto3 pandas matplotlib scikit-learn xgboost lightgbm joblib

      - name: ⚙️ Run Feature Selection
        run: python scripts/feature_selection.py
