name: Hyperparameter Tune Logistic Regression

on:
  push:
    branches:
      - main
    paths:
      - scripts/hpt_logistic_regression.py
      - cicd/run_hpt_job.py
      - .github/workflows/hpt.yml

jobs:
  hpt:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install boto3 sagemaker scikit-learn matplotlib

      - name: Run HPT job
        run: python cicd/run_hpt_job.py
