name: Train Models

on:
  push:
    branches:
      - main
    paths:
      - scripts/train.py
      - cicd/run_training_job.py
      - .github/workflows/train.yml

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install boto3 sagemaker scikit-learn matplotlib xgboost lightgbm joblib

      - name: Run training job
        run: python cicd/run_training_job.py
